services:
  db:
    image: postgres:16.9-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  web:
    build: .
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_DATABASE: postgres
      DB_USERNAME: postgres
    command: ["make", "ci-lint", "test-coverage"]
