services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
    depends_on:
      - db
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_DATABASE: postgres
      DB_USERNAME: postgres
    command: ["make", "lint-ci", "test-coverage"]
