---

version: '3'

services:

  db:
    image: postgres:14.4-bullseye
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build:
      context: .
    command: make start
    ports:
      - "8000:8000"
    # env_file: '.env'
    volumes:
      # - "web_static:/web/priv/static"
      - ".:/app"
      # - "~/.bash_history:/root/.bash_history:cached"
      # - ".bashrc:/root/.bashrc:cached"
      - "/tmp:/tmp"
    depends_on:
      - db

volumes:
  pgdata:
  # web_node_modules:
  # web_static:
  # app_build:
  # app_deps:
