services:

  db:
    image: postgres:16.9-bullseye
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      initial:
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
    command: make start
    ports:
      - "8000:8000"
    # env_file: '.env'
    volumes:
      - ".:/app"
      - "/tmp:/tmp"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      initial:

volumes:
  pgdata:

networks:
  initial:
