services:
  app:
    build: .
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_DATABASE: postgres
      DB_USERNAME: postgres
    command: ["make", "composer exec --verbose phpcs -- app tests", "test-coverage"]

  db:
    image: postgres:16.9-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
