name: PHP CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions: ['8.3']

    steps:
      - uses: actions/checkout@v4

      - name: Set up PHP ${{ matrix.php-versions }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}

      - name: PHP Security Checker
        uses: StephaneBour/actions-php-security-checker@1.1

      - name: Create SQLite Database
        run: touch database/database.sqlite

      - name: Setup project
        run: make setup

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Clear Config Cache
        run: php artisan config:clear

      - name: Run Migrations
        run: php artisan migrate --force

      - name: Check lint
        run: make lint

      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: make test-coverage
