name: SonarQube CI

on:
  workflow_run:
    workflows: ["PHP CI"]
    types:
      - completed

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: make test-coverage

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
